services:
  mongodb:
    image: mongo:latest
    container_name: 'hashview-mongodb'
    ports:
      - "27017:27017"
    restart: always
    stdin_open: true
    tty: true

  server:
    build: './server'
    container_name: 'hashview-server'
    ports:
      - '5000:5000'
    stdin_open: true
    tty: true
    env_file:
      - ./server/.env
    depends_on:
      - mongodb

  client:
    build: './client'
    container_name: 'hashview-client'
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true

  nginx:
    build: nginx
    container_name: 'hashview-nginx'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./mountpoint/certs/www.hash-view.com:/etc/letsencrypt/live/www.hash-view.com
    depends_on:
      - server
      - client
    stdin_open: true
    tty: true
